/**
 * Default Protocol Definitions
 *
 * Protocol entities define communication standards with framing,
 * message structures, and command templates.
 */

import type { Protocol } from "../protocolTypes";

const now = Date.now();

// ============================================================================
// AT COMMANDS PROTOCOL
// ============================================================================

export const PROTOCOL_AT_COMMANDS: Protocol = {
  id: "proto-at-commands",
  name: "AT Commands",
  description: "Standard AT command protocol for modems and ESP devices",
  version: "1.0",
  icon: "terminal",
  tags: ["modem", "esp32", "wifi", "bluetooth"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: "\r\n",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    {
      id: "cmd-at-check",
      type: "SIMPLE",
      name: "AT Check",
      description: "Basic AT check command",
      tags: ["basic"],
      createdAt: now,
      updatedAt: now,
      payload: "AT",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-at-version",
      type: "SIMPLE",
      name: "Get Version",
      description: "Get firmware version",
      tags: ["info"],
      createdAt: now,
      updatedAt: now,
      payload: "AT+GMR",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 3000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-at-reset",
      type: "SIMPLE",
      name: "Reset Device",
      description: "Software reset the device",
      tags: ["control"],
      createdAt: now,
      updatedAt: now,
      payload: "AT+RST",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 5000,
        successPattern: "ready",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-at-wifi-scan",
      type: "SIMPLE",
      name: "Scan WiFi Networks",
      description: "List available WiFi access points",
      tags: ["wifi"],
      createdAt: now,
      updatedAt: now,
      payload: "AT+CWLAP",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 10000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
  ],
};

// ============================================================================
// MODBUS RTU PROTOCOL
// ============================================================================

export const PROTOCOL_MODBUS_RTU: Protocol = {
  id: "proto-modbus-rtu",
  name: "Modbus RTU",
  description: "Industrial protocol for PLCs, sensors, and automation devices",
  version: "1.0",
  icon: "cpu",
  author: "Modbus Organization",
  sourceUrl: "https://modbus.org/specs.php",
  tags: ["industrial", "plc", "sensor", "automation"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "TIMEOUT",
    timeout: {
      silenceMs: 4,
      minBytes: 4,
    },
  },
  messageStructures: [
    {
      id: "struct-read-holding-req",
      name: "Read Holding Registers Request",
      description: "Function code 0x03 request",
      encoding: "BINARY",
      byteOrder: "BE",
      elements: [
        {
          id: "el-address",
          name: "address",
          description: "Slave address",
          size: 1,
          config: {
            type: "ADDRESS",
            range: { min: 1, max: 247 },
            broadcastValue: 0,
          },
        },
        {
          id: "el-function",
          name: "function",
          description: "Function code",
          size: 1,
          config: {
            type: "STATIC",
            value: [3],
          },
        },
        {
          id: "el-start-addr",
          name: "startAddress",
          description: "Starting register address",
          size: 2,
          config: {
            type: "FIELD",
            dataType: "UINT16",
          },
        },
        {
          id: "el-quantity",
          name: "quantity",
          description: "Number of registers to read",
          size: 2,
          config: {
            type: "FIELD",
            dataType: "UINT16",
          },
        },
        {
          id: "el-crc",
          name: "crc",
          description: "CRC-16 checksum",
          size: 2,
          config: {
            type: "CHECKSUM",
            algorithm: "CRC16_MODBUS",
            includeElements: [
              "el-address",
              "el-function",
              "el-start-addr",
              "el-quantity",
            ],
          },
        },
      ],
    },
  ],
  commands: [
    {
      id: "cmd-modbus-read-holding",
      type: "STRUCTURED",
      name: "Read Holding Registers",
      description: "Read holding registers (FC 0x03)",
      tags: ["read"],
      createdAt: now,
      updatedAt: now,
      messageStructureId: "struct-read-holding-req",
      parameters: [
        {
          name: "address",
          label: "Slave Address",
          type: "INTEGER",
          defaultValue: 1,
          min: 1,
          max: 247,
        },
        {
          name: "startAddress",
          label: "Start Address",
          type: "INTEGER",
          defaultValue: 0,
          min: 0,
          max: 65535,
        },
        {
          name: "quantity",
          label: "Quantity",
          type: "INTEGER",
          defaultValue: 2,
          min: 1,
          max: 125,
        },
      ],
      bindings: [
        { elementId: "el-address", parameterName: "address" },
        { elementId: "el-start-addr", parameterName: "startAddress" },
        { elementId: "el-quantity", parameterName: "quantity" },
      ],
      validation: {
        enabled: true,
        timeout: 1000,
      },
    },
  ],
};

// ============================================================================
// SCPI INSTRUMENT PROTOCOL
// ============================================================================

export const PROTOCOL_SCPI: Protocol = {
  id: "proto-scpi",
  name: "SCPI Commands",
  description:
    "Standard Commands for Programmable Instruments - for lab equipment",
  version: "1.0",
  icon: "activity",
  tags: ["instrument", "lab", "measurement", "scpi"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: "\n",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    {
      id: "cmd-scpi-idn",
      type: "SIMPLE",
      name: "Identify",
      description: "Query instrument identification",
      tags: ["basic", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "*IDN?",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 3000,
      },
      extractVariables: [],
    },
    {
      id: "cmd-scpi-rst",
      type: "SIMPLE",
      name: "Reset",
      description: "Reset instrument to default state",
      tags: ["control"],
      createdAt: now,
      updatedAt: now,
      payload: "*RST",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: false,
        timeout: 5000,
      },
      extractVariables: [],
    },
    {
      id: "cmd-scpi-opc",
      type: "SIMPLE",
      name: "Operation Complete?",
      description: "Query operation complete status",
      tags: ["query", "status"],
      createdAt: now,
      updatedAt: now,
      payload: "*OPC?",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "1",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-scpi-error",
      type: "SIMPLE",
      name: "Query Error",
      description: "Query system error queue",
      tags: ["query", "error"],
      createdAt: now,
      updatedAt: now,
      payload: ":SYST:ERR?",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
      },
      extractVariables: [],
    },
    {
      id: "cmd-scpi-meas-vdc",
      type: "SIMPLE",
      name: "Measure DC Voltage",
      description: "Measure DC voltage",
      tags: ["measurement", "voltage"],
      createdAt: now,
      updatedAt: now,
      payload: ":MEAS:VOLT:DC?",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 5000,
      },
      extractVariables: [
        {
          variableName: "voltage",
          pattern: "([\\d.+-E]+)",
        },
      ],
    },
  ],
};

// ============================================================================
// MARLIN G-CODE PROTOCOL (3D Printers)
// ============================================================================

export const PROTOCOL_MARLIN: Protocol = {
  id: "proto-marlin",
  name: "Marlin G-code",
  description: "G-code protocol for 3D printers running Marlin firmware",
  version: "1.0",
  icon: "printer",
  tags: ["3d-printer", "gcode", "marlin", "cnc"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: "\n",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    {
      id: "cmd-marlin-temp",
      type: "SIMPLE",
      name: "Report Temperatures",
      description: "Get current extruder and bed temperatures",
      tags: ["temperature", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "M105",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "T:",
        successPatternType: "CONTAINS",
      },
      extractVariables: [
        {
          variableName: "extruderTemp",
          pattern: "T:([\\d.]+)",
        },
        {
          variableName: "bedTemp",
          pattern: "B:([\\d.]+)",
        },
      ],
    },
    {
      id: "cmd-marlin-home",
      type: "SIMPLE",
      name: "Home All Axes",
      description: "Home X, Y, and Z axes",
      tags: ["motion", "homing"],
      createdAt: now,
      updatedAt: now,
      payload: "G28",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 60000,
        successPattern: "ok",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-marlin-position",
      type: "SIMPLE",
      name: "Report Position",
      description: "Get current position",
      tags: ["position", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "M114",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
      },
      extractVariables: [
        {
          variableName: "posX",
          pattern: "X:([\\d.-]+)",
        },
        {
          variableName: "posY",
          pattern: "Y:([\\d.-]+)",
        },
        {
          variableName: "posZ",
          pattern: "Z:([\\d.-]+)",
        },
      ],
    },
    {
      id: "cmd-marlin-set-hotend",
      type: "SIMPLE",
      name: "Set Hotend Temperature",
      description: "Set extruder temperature (no wait)",
      tags: ["temperature", "control"],
      createdAt: now,
      updatedAt: now,
      payload: "M104 S${temp}",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [
        {
          name: "temp",
          label: "Temperature (°C)",
          type: "INTEGER",
          defaultValue: 200,
          min: 0,
          max: 300,
        },
      ],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "ok",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-marlin-set-bed",
      type: "SIMPLE",
      name: "Set Bed Temperature",
      description: "Set bed temperature (no wait)",
      tags: ["temperature", "control"],
      createdAt: now,
      updatedAt: now,
      payload: "M140 S${temp}",
      mode: "TEXT",
      lineEnding: "LF",
      parameters: [
        {
          name: "temp",
          label: "Temperature (°C)",
          type: "INTEGER",
          defaultValue: 60,
          min: 0,
          max: 120,
        },
      ],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "ok",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
  ],
};

// ============================================================================
// ELM327 OBD-II PROTOCOL
// ============================================================================

export const PROTOCOL_ELM327: Protocol = {
  id: "proto-elm327",
  name: "ELM327 OBD-II",
  description: "OBD-II diagnostics via ELM327 adapter",
  version: "1.0",
  icon: "car",
  tags: ["automotive", "obd", "diagnostics", "elm327"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: ">",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    {
      id: "cmd-elm-reset",
      type: "SIMPLE",
      name: "Reset",
      description: "Reset ELM327 adapter",
      tags: ["control", "reset"],
      createdAt: now,
      updatedAt: now,
      payload: "ATZ",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 3000,
        successPattern: "ELM327",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-elm-echo-off",
      type: "SIMPLE",
      name: "Echo Off",
      description: "Disable command echo",
      tags: ["config"],
      createdAt: now,
      updatedAt: now,
      payload: "ATE0",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 1000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-elm-auto-proto",
      type: "SIMPLE",
      name: "Auto Protocol",
      description: "Set automatic protocol detection",
      tags: ["config"],
      createdAt: now,
      updatedAt: now,
      payload: "ATSP0",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 1000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-obd-rpm",
      type: "SIMPLE",
      name: "Engine RPM",
      description: "PID 0C: Engine RPM",
      tags: ["pid", "engine"],
      createdAt: now,
      updatedAt: now,
      payload: "010C",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
      },
      extractVariables: [
        {
          variableName: "rpm",
          pattern: "41 0C ([0-9A-F]{2}) ([0-9A-F]{2})",
          transform: "(parseInt($1, 16) * 256 + parseInt($2, 16)) / 4",
        },
      ],
    },
    {
      id: "cmd-obd-speed",
      type: "SIMPLE",
      name: "Vehicle Speed",
      description: "PID 0D: Vehicle Speed (km/h)",
      tags: ["pid", "speed"],
      createdAt: now,
      updatedAt: now,
      payload: "010D",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
      },
      extractVariables: [
        {
          variableName: "speed",
          pattern: "41 0D ([0-9A-F]{2})",
          transform: "parseInt($1, 16)",
        },
      ],
    },
    {
      id: "cmd-obd-coolant",
      type: "SIMPLE",
      name: "Coolant Temperature",
      description: "PID 05: Engine Coolant Temperature",
      tags: ["pid", "temperature"],
      createdAt: now,
      updatedAt: now,
      payload: "0105",
      mode: "TEXT",
      lineEnding: "CR",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
      },
      extractVariables: [
        {
          variableName: "coolantTemp",
          pattern: "41 05 ([0-9A-F]{2})",
          transform: "parseInt($1, 16) - 40",
        },
      ],
    },
  ],
};

// ============================================================================
// GPS NMEA PROTOCOL
// ============================================================================

export const PROTOCOL_GPS_NMEA: Protocol = {
  id: "proto-gps-nmea",
  name: "GPS NMEA",
  description: "NMEA 0183 protocol for GPS receivers",
  version: "1.0",
  icon: "map-pin",
  tags: ["gps", "navigation", "nmea", "location"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: "\r\n",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    {
      id: "cmd-gps-gga",
      type: "SIMPLE",
      name: "GGA Fix Data",
      description: "GPS fix data - position, quality, satellites",
      tags: ["position", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "$GPGGA",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: false,
        timeout: 2000,
      },
      extractVariables: [
        {
          variableName: "latitude",
          pattern: "\\$GPGGA,[^,]*,([^,]*),([NS])",
        },
        {
          variableName: "longitude",
          pattern: "\\$GPGGA,[^,]*,[^,]*,[^,]*,([^,]*),([EW])",
        },
      ],
    },
    {
      id: "cmd-gps-rmc",
      type: "SIMPLE",
      name: "RMC Position/Velocity",
      description: "Recommended Minimum Specific GPS/Transit Data",
      tags: ["position", "velocity", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "$GPRMC",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: false,
        timeout: 2000,
      },
      extractVariables: [],
    },
    {
      id: "cmd-gps-gsa",
      type: "SIMPLE",
      name: "GSA DOP/Active Satellites",
      description: "GPS DOP and active satellites",
      tags: ["satellites", "query"],
      createdAt: now,
      updatedAt: now,
      payload: "$GPGSA",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: false,
        timeout: 2000,
      },
      extractVariables: [],
    },
  ],
};

// ============================================================================
// ESP32 TEST DEVICE PROTOCOL (Multi-mode emulator)
// ============================================================================

export const PROTOCOL_ESP32_TEST_DEVICE: Protocol = {
  id: "proto-esp32-test-device",
  name: "ESP32 Test Device",
  description:
    "Setup and mode switching commands for the ESP32 Serial Protocol Tester",
  version: "1.0",
  icon: "cpu",
  tags: ["esp32", "test", "emulator", "multi-mode"],
  createdAt: now,
  updatedAt: now,
  framing: {
    strategy: "DELIMITER",
    delimiter: {
      sequence: "\r\n",
      position: "SUFFIX",
      includeInFrame: false,
    },
  },
  messageStructures: [],
  commands: [
    // Setup Commands
    {
      id: "cmd-test-help",
      type: "SIMPLE",
      name: "Show Help",
      description: "Display all available commands",
      tags: ["setup", "help"],
      createdAt: now,
      updatedAt: now,
      payload: "HELP",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: { enabled: false, timeout: 2000 },
      extractVariables: [],
    },
    {
      id: "cmd-test-status",
      type: "SIMPLE",
      name: "Device Status",
      description: "Show current mode, WiFi status, and sensor values",
      tags: ["setup", "status"],
      createdAt: now,
      updatedAt: now,
      payload: "STATUS",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: { enabled: false, timeout: 2000 },
      extractVariables: [
        { variableName: "mode", pattern: "Mode: (\\w+)" },
        { variableName: "wifi", pattern: "WiFi: (\\w+)" },
      ],
    },
    // Mode Switch Commands
    {
      id: "cmd-test-mode-echo",
      type: "SIMPLE",
      name: "Switch to Echo Mode",
      description: "Switch to echo/loopback mode",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=ECHO",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-at",
      type: "SIMPLE",
      name: "Switch to AT Mode",
      description: "Switch to AT command mode",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=AT",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-scpi",
      type: "SIMPLE",
      name: "Switch to SCPI Mode",
      description: "Switch to SCPI instrument emulation",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=SCPI",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-marlin",
      type: "SIMPLE",
      name: "Switch to Marlin Mode",
      description: "Switch to 3D printer Marlin G-code emulation",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=MARLIN",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-elm327",
      type: "SIMPLE",
      name: "Switch to ELM327 Mode",
      description: "Switch to ELM327 OBD-II adapter emulation",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=ELM327",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-gps",
      type: "SIMPLE",
      name: "Switch to GPS Mode",
      description: "Switch to NMEA GPS sentence generator",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=GPS",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-mode-modbus",
      type: "SIMPLE",
      name: "Switch to Modbus Mode",
      description: "Switch to Modbus RTU slave emulation",
      tags: ["mode"],
      createdAt: now,
      updatedAt: now,
      payload: "MODE=MODBUS",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [],
      validation: {
        enabled: true,
        timeout: 2000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    // Simulation Data Commands
    {
      id: "cmd-test-set-temp",
      type: "SIMPLE",
      name: "Set Temperature",
      description: "Set simulated temperature value",
      tags: ["simulation"],
      createdAt: now,
      updatedAt: now,
      payload: "SET_TEMP=${temp}",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [
        {
          name: "temp",
          label: "Temperature (°C)",
          type: "FLOAT",
          defaultValue: 25.0,
          min: -40,
          max: 100,
        },
      ],
      validation: {
        enabled: true,
        timeout: 1000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
    {
      id: "cmd-test-set-rpm",
      type: "SIMPLE",
      name: "Set RPM",
      description: "Set simulated engine RPM value",
      tags: ["simulation"],
      createdAt: now,
      updatedAt: now,
      payload: "SET_RPM=${rpm}",
      mode: "TEXT",
      lineEnding: "CRLF",
      parameters: [
        {
          name: "rpm",
          label: "RPM",
          type: "INTEGER",
          defaultValue: 3000,
          min: 0,
          max: 10000,
        },
      ],
      validation: {
        enabled: true,
        timeout: 1000,
        successPattern: "OK",
        successPatternType: "CONTAINS",
      },
      extractVariables: [],
    },
  ],
};

// ============================================================================
// EXPORT ALL DEFAULT PROTOCOLS
// ============================================================================

export const DEFAULT_PROTOCOLS: Protocol[] = [
  PROTOCOL_ESP32_TEST_DEVICE,
  PROTOCOL_AT_COMMANDS,
  PROTOCOL_SCPI,
  PROTOCOL_MARLIN,
  PROTOCOL_ELM327,
  PROTOCOL_GPS_NMEA,
  PROTOCOL_MODBUS_RTU,
];
