codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true

flags:
  frontend:
    paths:
      - src/
    carryforward: true
  rust:
    paths:
      - src-tauri/src/
    carryforward: true

ignore:
  - "src/lib/tauri/bindings.ts"
  - "src/tests/**"
  - "**/*.test.*"
  - "**/*.spec.*"
